# Generated by Django 2.1.5 on 2020-03-30 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_stream', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.TextField(max_length=800),
        ),
    ]
